### ISSUE TITLE
List of abbreviations and symbols not being generated

### ISSUE THREAD

**Issue by sandipan211** [Jue-Xu/Latex-Template-for-Scientific-Style-Book#2]
Hi,
Thanks for making such a useful template. However, the list of abbreviations and glossaries is not being generated when I compile the project in Overleaf. Primarily, I'm compiling the exact template source file you gave but getting warnings in the preamble file (see image for line numbers), which is why there are other warnings while defining every glossary word you have in your other files. My guess is that there might be some problems in Overleaf in using commands like \GlsXtrLoadResources from bib2gls package. Is it not supported on Overleaf yet?

Kindly help me out, and tell me how I can fix it. Looking forward to your reply.
P.S. I'm new to LaTeX. It'll be helpful if you write down the steps I need to do.
Edit: I saw your latexmkrc configuration file but I don't know how to add it. Please help.
![Screenshot (67)](https://user-images.githubusercontent.com/30040548/167267276-b8fc76a1-0893-4fbf-9f72-4aeb014c1d53.png)

**Comment by Jue-Xu** [comment]
Hi, I have the same issue about gls when compiling my template on Overleaf because my template relys on the package {glossaries-extra}. I am not sure whether Overleaf can support it by any workaround. I usually work on my notes on a local machine instead of Overleaf, so I can compile the glossary with commands such as 
```
pdflatex glossaries.tex
makeglossaries glossaries
pdflatex glossaries.tex
```
If you don't use glossaries or symbols heavily, you could follow the tutorial on Overleaf about  glossaries https://www.overleaf.com/learn/latex/Glossaries. It can generate a list of glossary on Overleaf without any external commands.

Latexmk is a tool included in TexLive which helps users compile "big" Latex projects easily. With Latexmk, you don't need to run a sequence of commands in the shell to update (compile) your pdf. Latexmkrc is its configuration file that tells Latexmk how to compile. However, I am not an expert about Latex language. All the latexmkrc configurations are all from Google or Stackoverflow. If I remember correctly, they are from 
https://tex.stackexchange.com/questions/1226/how-to-make-latexmk-use-makeglossaries
https://tex.stackexchange.com/questions/400325/latexmkrc-for-bib2gls/401979#401979
https://mirror.las.iastate.edu/tex-archive/support/latexmk/example_rcfiles/bib2gls_latexmkrc

Let me know if you have any question about my reply or you find solutions.

**Comment by Jue-Xu** [comment]
I guess you didn't run the command
```
pdflatex notes.tex
bib2gls notes
pdflatex notes.tex
```
to compile the gls. To show the steps, I uploaded a short video to YouTube (https://youtu.be/_QX-ci_uA_s). If you rely heavily on glossaries and don't want to run the command every time, you could spend some time to configure VSCode and Latexmk which makes the work flow easier. If you don't have many glossaries,  the glossary package (https://www.overleaf.com/learn/latex/Glossaries) might be a better choice which can be compiled on Overleaf with ease.

**Comment by sandipan211** [comment]
It's finally working! Thanks for the short video...that's all I needed! Once again, thanks for this wonderful template you've made, and for the help!

**Comment by Jue-Xu** [comment]
No problem! I am glad that you like this template. If you feel it is helpful, give this repository a star and probably acknowledge it in your notes such that more people know and make use of this template.
