### ISSUE TITLE
Chapter number in the mini TOC is one greater than it should be when built locally

### ISSUE THREAD

**Issue by cuihantao** [Jue-Xu/Latex-Template-for-Scientific-Style-Book#4]
Hi Jue,

Thanks for making this amazing template! I tried to build it locally in VS Code with your setting using the `latexmk` recipe for LaTeX Workshop. I did not create the `latexmkrc` file because for some reason it breaks the recipe.

The issue I'm seeing is that the chapter number in the mini toc is one greater than the actual chapter number. It looks like the line `    \adjustmtc[2]% chp number shift for mini-toc` is the* cause, and changing the adjustment to `1` fixes the issue on my end. On Overleaf, however, your code works correctly.

I'm using MikTex on Windows with all packages upgraded to the most recent version.

**Comment by Jue-Xu** [comment]
Thanks for your feedback! 

1. You can set the appropriate parameter for `\adjustmtc[2]% chp number shift for mini-toc` if necessary. I use `\adjustmtc[2]` because I have a preface counted as chapter 0. The `real` chapter number is somewhat different from the minitoc chapter number, so `\adjustmtc[2]` serves as a workaround. There might be some better solution.

2. The latexmk and VS Code configuration in the README is incomplete. I should take some time to polish it. Does your VS Code work well this recipe?

3. I didn't see the difference between my local version and the Overleaf version. Did you, for example, hide the preface chapter on your local machine?

**Comment by cuihantao** [comment]
I didn't comment out Chapter 0. When the Acronyms and Symbols list was not correctly built, in Chapter 0, the mini-toc in Chapter 0 labels the sections as 1.1, 1.2, etc.

When I later figured out how to build the Acronyms and Symbols, your code `\adjustmtc[2]` then generates the correct mini-toc.

I didn't end up using the `latexmkrc` file but added a `build glossaries` tool in the LaTeX Workshop configuration:

```
    "latex-workshop.latex.recipes": [
        {
            "name": "latexmk -> makeglossary -> latexmk",
            "tools": [
                "pdflatex",
                "makeglossaries",
                "pdflatex"
            ]
        }
    ],
    "latex-workshop.latex.tools":[
    {
      "name": "pdflatex",
      "command": "pdflatex",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "%DOC%"
      ],
      "env": {}
    },
    {
      "name": "makeglossaries",
      "command": "makeglossaries",
      "args": ["%DOCFILE%"],
      "env": {}
    }
    ]
```

It mimics your commands and appears to work.

```
pdflatex notes.tex
makeglossaries notes
pdflatex notes.tex
```
